const sharedCaveat =
  "16タイプ風の娯楽的なコミュニケーション類型です。医学的・科学的診断として扱わず、個人差を優先します。";

export const personaCatalog = {
  INFJ: {
    label: "INFJ風",
    nickname: "深い精神的絆を求める洞察者",
    summary: "表面的なやり取りより、誠実さ・意味・未来への共感を大切にするタイプ。静かな対話の中で、相手の本音や可能性を丁寧に見つめます。",
    relationshipNeeds: ["深い理解", "誠実さ", "将来への志や価値観の共有"],
    communication: ["一対一の落ち着いた会話を好む", "抽象的な意味や背景に反応しやすい", "軽い冗談より、本音を丁寧に扱われると安心する"],
    conflictPattern: "対立そのものを苦痛に感じやすい。すぐ結論を迫られるより、落ち着く時間と誠実な再対話が必要。",
    reassuranceStyle: "深い対話、ビジョンへの共感、言葉と行動が一致していること。",
    dateHints: ["沈黙を焦って埋めない", "気持ちを言い換えて確認する", "急な告白より、安心できる継続感を示す"],
    goodLines: ["その話、大切にしてきたことなんだね", "急がなくていいよ。聞ける範囲で教えて", "次も落ち着いて話せる場所にしよう"],
    badLines: ["考えすぎじゃない？", "つまり結論は？", "重い話は苦手だから楽しくいこう"],
    scoringBias: { empathize: 1.2, playful: 0.8, concrete: 1, action: 0.75 },
    citations: ["Love Styles", "How Personality Types Handle Relationship Conflict"],
    caveat: sharedCaveat,
  },
  ENFP: {
    label: "ENFP風",
    nickname: "可能性を信じる自由なインスピレーター",
    summary: "好奇心と熱量で場を明るくするタイプ。相手の夢や個性を面白がり、予想外の展開も一緒に楽しみたい気持ちが強めです。",
    relationshipNeeds: ["励まし", "オープンマインド", "感情的な深いつながり"],
    communication: ["発想を広げる会話が得意", "否定から入られると熱量が下がりやすい", "自由度のある提案に心が動きやすい"],
    conflictPattern: "感情的な正直さを求める一方、束縛や冷たい否定には強く反応しやすい。",
    reassuranceStyle: "質の高い時間、肯定的な言葉、可能性を一緒に広げる姿勢。",
    dateHints: ["まず楽しそうに受ける", "選択肢を広げる提案をする", "細かい制約より一緒に試す姿勢を見せる"],
    goodLines: ["それ最高。今度一緒にやってみたい", "その話もっと聞きたい、ワクワクする", "予定変えて寄り道するのもありだね"],
    badLines: ["現実的に無理でしょ", "ちゃんと計画してからにしよう", "テンション高すぎない？"],
    scoringBias: { empathize: 0.9, playful: 1.25, concrete: 0.85, action: 1.05 },
    citations: ["What Each Myers-Briggs Type Needs in a Relationship", "The INFJ and ENFP Relationship"],
    caveat: sharedCaveat,
  },
  ISTJ: {
    label: "ISTJ風",
    nickname: "理知的で誠実な守護者",
    summary: "信頼は言葉より行動で積み上げると感じるタイプ。具体性、約束、時間への配慮を大切にします。",
    relationshipNeeds: ["献身", "誠実さ", "計画通りの安定した関係"],
    communication: ["具体的な提案を好む", "急な変更や雑な約束に不安を感じやすい", "派手さより継続的な誠実さを評価する"],
    conflictPattern: "感情より事実を優先しがち。感情的に責められると距離を取りやすい。",
    reassuranceStyle: "有言実行、変わらないルーチン、現実的なサポート。",
    dateHints: ["日時や場所を具体的にする", "約束を守る意思を言葉にする", "相手の準備や段取りを尊重する"],
    goodLines: ["来週土曜の午後ならどう？無理なら別日でも大丈夫", "ちゃんと考えて誘いたかった", "時間を作ってくれてありがとう"],
    badLines: ["いつか適当に行こう", "細かいことは気にしなくてよくない？", "ノリで決めようよ"],
    scoringBias: { empathize: 0.95, playful: 0.75, concrete: 1.25, action: 0.85 },
    citations: ["Love Styles", "What Each Myers-Briggs Type Needs in a Relationship"],
    caveat: sharedCaveat,
  },
  ESTP: {
    label: "ESTP風",
    nickname: "スリルと体験を愛する行動派",
    summary: "考え込むより、まず体験して距離を縮めたいタイプ。テンポ、率直さ、その場の楽しさを大切にします。",
    relationshipNeeds: ["共通の体験", "熱意", "退屈しない刺激"],
    communication: ["長い説明より体験の提案に反応しやすい", "重すぎる空気や遠回しな確認が続くと退屈しやすい", "明るく率直な好意にテンポよく返しやすい"],
    conflictPattern: "対立を恐れず、その場で決着をつけたい。感情が強く出ても長く引きずらないことが多い。",
    reassuranceStyle: "一緒に動くこと、スキンシップ、楽しい体験の共有。",
    dateHints: ["短く率直に誘う", "一緒にできる体験を提案する", "深刻にしすぎず、その場の反応を見る"],
    goodLines: ["次はそこ行こう。まず試してみたい", "話してたら行きたくなってきた", "今度はもっと動けるデートにしよう"],
    badLines: ["この関係を定義したいから朝まで話そう", "察してほしい", "失敗したらどうするか先に全部決めたい"],
    scoringBias: { empathize: 0.8, playful: 1.05, concrete: 0.9, action: 1.25 },
    citations: ["Love Styles", "How Different Personality Types Start Relationships"],
    caveat: sharedCaveat,
  },
  INTJ: {
    label: "INTJ風",
    nickname: "論理と未来を見据える戦略家",
    summary: "知的な刺激と自立した距離感に安心するタイプ。関係も長期的に設計し、言葉の一貫性を重視します。",
    relationshipNeeds: ["知的な刺激", "一人時間の尊重", "正直なフィードバック"],
    communication: ["意図が明確な会話を好む", "過度な感情確認や干渉に疲れやすい", "自立した相手に惹かれやすい"],
    conflictPattern: "問題を客観的に分析して解決しようとする。感情的な訴えだけだと受け取り損ねやすい。",
    reassuranceStyle: "実用的な手助け、質の高い時間、論理と敬意のある対話。",
    dateHints: ["意図を簡潔に伝える", "相手の時間と集中を尊重する", "知的な深掘りを楽しむ"],
    goodLines: ["その考え方、筋が通っていて面白い", "無理に合わせなくて大丈夫。予定は合理的に決めよう", "なぜそう考えたのか聞きたい"],
    badLines: ["普通はこうでしょ", "もっと気持ちで動こうよ", "全部合わせてくれないと不安"],
    scoringBias: { empathize: 0.85, playful: 0.75, concrete: 1.15, action: 0.95 },
    citations: ["Love Styles", "What's Your MBTI's Best Communication Style?"],
    caveat: sharedCaveat,
  },
  INFP: {
    label: "INFP風",
    nickname: "理想と価値観を紡ぐ夢想家",
    summary: "心の純度や価値観の一致を重視するタイプ。急かされず、安心できる場で少しずつ内面を開きます。",
    relationshipNeeds: ["誠実さ", "価値観の共有", "創造的な自由"],
    communication: ["共感と意味づけを重視する", "強い批判や急な結論に敏感", "創作や理想の話で距離が縮まりやすい"],
    conflictPattern: "感情を強く感じるが、すぐ言語化できず黙り込むことがある。",
    reassuranceStyle: "肯定的な言葉、静かな二人時間、価値観を尊重する態度。",
    dateHints: ["価値観を尊重する", "急かさず余白を残す", "好きなものの背景を聞く"],
    goodLines: ["その世界観、あなたらしくて素敵だね", "無理に言葉にしなくても大丈夫", "大切にしている理由を聞いてみたい"],
    badLines: ["理想高すぎ", "現実を見なよ", "早く決めて"],
    scoringBias: { empathize: 1.2, playful: 0.85, concrete: 0.9, action: 0.75 },
    citations: ["Love Styles", "What Personality Types Really Want in a Partner"],
    caveat: sharedCaveat,
  },
  ENFJ: {
    label: "ENFJ風",
    nickname: "愛を導き相手を輝かせる主人公",
    summary: "相手の成長や感情に目を配り、関係を前向きに育てたいタイプ。感謝や熱意が伝わると大きく安心します。",
    relationshipNeeds: ["共感", "親密なつながり", "明確な目標への励まし"],
    communication: ["温度感のあるリアクションを好む", "感謝や配慮が伝わると安心する", "無関心や冷たい反応に傷つきやすい"],
    conflictPattern: "相手の感情を優先し、自分の要求を後回しにしがち。過干渉にも注意。",
    reassuranceStyle: "肯定的な言葉、深い対話、感謝を明確に伝えること。",
    dateHints: ["感謝を明確に伝える", "相手の配慮に気づく", "将来の小さな楽しみを共有する"],
    goodLines: ["気づかってくれてありがとう", "一緒にいると前向きになれる", "次もあなたが楽しめる場所を考えたい"],
    badLines: ["別にどっちでもいい", "そこまで気にしなくてよくない？", "重い気遣いだね"],
    scoringBias: { empathize: 1.1, playful: 1, concrete: 0.95, action: 0.9 },
    citations: ["Love Styles", "Myers-Briggs Type Indicator Communication Style Report"],
    caveat: sharedCaveat,
  },
  ENTJ: {
    label: "ENTJ風",
    nickname: "頂点を目指す野心的なパートナー",
    summary: "目標、成長、率直さに魅力を感じるタイプ。遠回しな駆け引きより、互いを高める明確な関係を好みます。",
    relationshipNeeds: ["敬意", "知的な刺激", "有能さへの信頼"],
    communication: ["目的や意思が見える会話を好む", "受け身すぎる態度に物足りなさを感じやすい", "尊敬できる強みや行動力に惹かれる"],
    conflictPattern: "問題を構造的に捉え、迅速に決着をつけたい。感情的なもたつきに苛立ちやすい。",
    reassuranceStyle: "質の高い時間、戦略的な支援、相手の成果を具体的に認めること。",
    dateHints: ["自分の希望も言う", "相手の努力や成果を具体的に認める", "次の提案を明確にする"],
    goodLines: ["私はまた会いたい。来週この予定はどう？", "そこまでやり切るの、尊敬する", "一緒にいると刺激をもらえる"],
    badLines: ["全部決めて", "なんとなくでいいよ", "強すぎて怖い"],
    scoringBias: { empathize: 0.85, playful: 0.9, concrete: 1.15, action: 1.1 },
    citations: ["Love Styles", "What Each Myers-Briggs Type Needs in a Relationship"],
    caveat: sharedCaveat,
  },
  INTP: {
    label: "INTP風",
    nickname: "知的好奇心に溢れる探求者",
    summary: "考える自由と知的な遊びを大切にするタイプ。感情を急に詰められるより、自然な興味でつながるほうが安心します。",
    relationshipNeeds: ["独立性", "知的な配慮", "誠実さ"],
    communication: ["仮説や仕組みを考える会話が好き", "感情確認を急がれると固まりやすい", "自由な思索を否定されないと安心する"],
    conflictPattern: "問題を論理的に解こうとして、相手の感情を置き去りにしがち。",
    reassuranceStyle: "知的な対話、肯定的な言葉、考える時間の尊重。",
    dateHints: ["面白がって質問する", "すぐ結論づけない", "考える時間を尊重する"],
    goodLines: ["その仮説、面白い。もう少し聞きたい", "答えを急がなくていいよ", "一緒に考えるの楽しい"],
    badLines: ["で、好きなの？今決めて", "理屈っぽいね", "普通にして"],
    scoringBias: { empathize: 0.95, playful: 0.95, concrete: 1, action: 0.8 },
    citations: ["Love Styles", "ENTP × INTP Compatibility Guide"],
    caveat: sharedCaveat,
  },
  ENTP: {
    label: "ENTP風",
    nickname: "知的な刺激を愛する会話の発明家",
    summary: "議論や新しい視点で関係を活性化させるタイプ。予定調和より、会話の跳躍や発見にときめきます。",
    relationshipNeeds: ["知的刺激", "自由度", "ユーモアと柔軟性"],
    communication: ["議論を遊びとして楽しむ", "型にはめられると冷めやすい", "反応のあるツッコミや提案に惹かれる"],
    conflictPattern: "議論が白熱しすぎると、相手を傷つけることがある。反論を人格否定にしない配慮が必要。",
    reassuranceStyle: "質の高い時間、知的なスリルを楽しむ余裕、自由を奪わないこと。",
    dateHints: ["会話をゲームのように楽しむ", "反論を人格否定にしない", "新しい選択肢を出す"],
    goodLines: ["その発想、悔しいけど面白い", "じゃあ別案も試してみよう", "話してるとアイデアが増えるね"],
    badLines: ["黙って従って", "変なこと言わないで", "議論する人は苦手"],
    scoringBias: { empathize: 0.8, playful: 1.2, concrete: 0.9, action: 1.05 },
    citations: ["Love Styles", "ENTP × INTP Compatibility Guide"],
    caveat: sharedCaveat,
  },
  ISFJ: {
    label: "ISFJ風",
    nickname: "献身的で温かな聞き役",
    summary: "小さな配慮や安心感を大切にするタイプ。相手の変化に気づき、穏やかな信頼を育てます。",
    relationshipNeeds: ["安全保障", "きめ細やかな配慮", "価値観の共有"],
    communication: ["感謝されると安心する", "急な変化や強い批判に不安を感じやすい", "相手の誠実さをよく見ている"],
    conflictPattern: "調和を重んじ、対立を避けがち。不満を溜めてから急に強く出ることがある。",
    reassuranceStyle: "肯定的な言葉、質の高い時間、小さな配慮への感謝。",
    dateHints: ["配慮に気づいて言葉にする", "予定変更は丁寧に伝える", "安心できる約束をする"],
    goodLines: ["気づいてくれてありがとう", "無理しなくて大丈夫。あなたのペースで", "次は落ち着ける場所にしよう"],
    badLines: ["それくらいやって当然", "急だけど今から来て", "細かいね"],
    scoringBias: { empathize: 1.15, playful: 0.8, concrete: 1.05, action: 0.75 },
    citations: ["Love Styles", "What Each Myers-Briggs Type Needs in a Relationship"],
    caveat: sharedCaveat,
  },
  ESFJ: {
    label: "ESFJ風",
    nickname: "調和を育む社交の達人",
    summary: "感謝、礼儀、気づかいを重視し、温かい相互配慮に心が動くタイプ。二人だけでなく周囲との調和も気にします。",
    relationshipNeeds: ["一緒に過ごす時間", "約束の遵守", "相互サポート"],
    communication: ["明るい反応と感謝を好む", "冷たい態度や放置に敏感", "周囲との調和も気にしやすい"],
    conflictPattern: "批判を個人的に受け止めやすく、調和回復に必死になりがち。",
    reassuranceStyle: "質の高い時間、手助けの行動、感謝を言葉にすること。",
    dateHints: ["楽しい気持ちを表情と言葉で出す", "相手の準備に感謝する", "次の予定も温かく提案する"],
    goodLines: ["今日すごく楽しい。誘ってくれてありがとう", "その気づかい、うれしかった", "また一緒に行きたい"],
    badLines: ["別に普通", "そんなに気を使わなくていいのに", "返信は気分次第"],
    scoringBias: { empathize: 1.05, playful: 1.05, concrete: 0.95, action: 0.9 },
    citations: ["Love Styles", "What Personality Types Really Want in a Partner"],
    caveat: sharedCaveat,
  },
  ISTP: {
    label: "ISTP風",
    nickname: "自律を愛する実践派",
    summary: "干渉されすぎない距離感で、実際に一緒に何かをする時間から親しさが育つタイプ。言葉より行動が響きやすいです。",
    relationshipNeeds: ["個人のスペース", "独立性", "共通の楽しみ"],
    communication: ["短く率直なやり取りを好む", "詰問や過度な感情表現に引きやすい", "自由を尊重されると安心する"],
    conflictPattern: "議論から距離を置き、一人で冷静になる時間を欲しがる。",
    reassuranceStyle: "自由を制限しないこと、実用的な行動、自然なスキンシップ。",
    dateHints: ["短く誘う", "相手のひとり時間を尊重する", "体験を共有する"],
    goodLines: ["無理に話さなくていいよ。歩きながらで", "次は実際にやってみよう", "自分のペースで大丈夫"],
    badLines: ["何考えてるか全部教えて", "冷たくない？", "毎日必ず連絡して"],
    scoringBias: { empathize: 0.85, playful: 0.9, concrete: 1, action: 1.15 },
    citations: ["Love Styles", "What Each Myers-Briggs Type Needs in a Relationship"],
    caveat: sharedCaveat,
  },
  ISFP: {
    label: "ISFP風",
    nickname: "今を彩る感性の芸術家",
    summary: "やわらかな感性と自由を大切にするタイプ。押しつけより、雰囲気や体験を一緒に味わう関係に惹かれます。",
    relationshipNeeds: ["親密さ", "自由", "価値観への理解"],
    communication: ["穏やかで思いやりのある会話を好む", "批判や説明責めに弱い", "五感や雰囲気の共有で距離が縮まりやすい"],
    conflictPattern: "批判を個人的に受け止めやすく、傷つくと黙り込みやすい。",
    reassuranceStyle: "肯定的な言葉、二人の時間、好みや感性を否定しない態度。",
    dateHints: ["感じたことをやわらかく共有する", "好みを否定しない", "静かな体験を一緒に味わう"],
    goodLines: ["その感じ方、素敵だね", "この雰囲気、一緒に味わえてうれしい", "無理に合わせなくていいよ"],
    badLines: ["センス変じゃない？", "もっとちゃんと説明して", "早く決めて"],
    scoringBias: { empathize: 1.1, playful: 0.9, concrete: 0.85, action: 0.95 },
    citations: ["Love Styles", "Feeling vs. Thinking Preference"],
    caveat: sharedCaveat,
  },
  ESTJ: {
    label: "ESTJ風",
    nickname: "信頼に応える頼れるリーダー",
    summary: "責任感、約束、実行力を重視するタイプ。あいまいさより、明確で誠実なやり取りに安心します。",
    relationshipNeeds: ["責任感", "忠誠心", "良き友人としての絆"],
    communication: ["明確さと実用性を好む", "無責任な態度に厳しい", "頼りがいや誠実さを評価する"],
    conflictPattern: "ルール違反や非効率に強く反応し、事実ベースで解決しようとする。",
    reassuranceStyle: "具体的な感謝、約束を守る行動、質の高い時間。",
    dateHints: ["時間や場所をはっきりさせる", "感謝と敬意を具体的に伝える", "自分の意思も明確にする"],
    goodLines: ["段取りしてくれて助かった。ありがとう", "私はまた会いたい。次はこの日どう？", "その責任感、かっこいいね"],
    badLines: ["まあ適当で", "遅れてもいいでしょ", "仕切りすぎ"],
    scoringBias: { empathize: 0.85, playful: 0.8, concrete: 1.2, action: 1.05 },
    citations: ["Love Styles", "What Each Myers-Briggs Type Needs in a Relationship"],
    caveat: sharedCaveat,
  },
  ESFP: {
    label: "ESFP風",
    nickname: "周囲を笑顔にする愛の体現者",
    summary: "明るい反応とその場の楽しさを大切にするタイプ。褒め言葉や一緒に盛り上がる体験で距離が縮まります。",
    relationshipNeeds: ["冒険", "ありのままの自分", "共感"],
    communication: ["表現豊かなリアクションを好む", "重い空気や否定が続くと冷めやすい", "体験と感情をその場で共有したい"],
    conflictPattern: "重苦しい雰囲気を避けがち。感情的に反応しても、長く引きずらない傾向。",
    reassuranceStyle: "肯定的な言葉、スキンシップ、一緒に楽しむ姿勢。",
    dateHints: ["表情と言葉で楽しさを出す", "一緒にできることを提案する", "褒める時は素直に短く"],
    goodLines: ["今日めちゃくちゃ楽しい", "それ似合ってる。雰囲気いいね", "次はもっと遊べる場所に行こう"],
    badLines: ["うるさいね", "先のことを真面目に決めよう", "浮かれすぎ"],
    scoringBias: { empathize: 0.85, playful: 1.15, concrete: 0.85, action: 1.15 },
    citations: ["Love Styles", "What Each Myers-Briggs Type Needs in a Relationship"],
    caveat: sharedCaveat,
  },
};
